config/routes.rb
Blog::Application.routes.draw do

  get "contacts/create"

  resources :posts do
    resources :comments
      resources :tags
  end
  resources :contacts

  root :to => "home#index"
  match "about_us" => "posts#about_us", :as => "about_us"
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :commenter, :post
  belongs_to :post
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name, :subject, :website

  validates :name,  :presence => true
  validates :email, :presence => true
  validates :message,  :presence => true
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title, :tags_attributes
 
  validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }

  has_many :comments, :dependent => :destroy
  has_many :tags

   accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
    
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery
  #before_filter :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with :name => "gagan", :password => "gagan", :except => [:index, :show]

	def create
	    @post = Post.find(params[:post_id])
	    @comment = @post.comments.create(params[:comment])
	    redirect_to post_path(@post)
  	end

  	def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  	def new
	  	@contact = Contact.new
	  	respond_to do |format|
	  		format.html  
	  	end
	end


	def create
		@contact = Contact.new(params[:contact])
		respond_to do |format|
			if @contact.save
				format.html { redirect_to new_contact_path, :notice => "Contact detail added successfully." }
			end
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_filter :authenticate_user!





  http_basic_authenticate_with :name => "gagan", :password => "gagan"
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end
end

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>
 
<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/_form.html.erb
<style>
.field div{
  color: black;
  font-style: bold;
  font-size: 15;
}
</style>


<%= form_for(@contact) do |contact_form| %>
  <% if @contact.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  <!-- Fields of Contact Form -->
  <div class="field">
    <%= contact_form.label :name %><br />
    <%= contact_form.text_field :name %>
  </div>
  <div class="field">
    <%= contact_form.label :email %><br />
    <%= contact_form.text_field :email, :placeholder => "your@email.com" %>
  </div>
  <div class="field">
    <%= contact_form.label :website %><br />
    <%= contact_form.text_field :website, :placeholder => "www.yourwebsite.com" %>
  </div>
  <div class="field">
    <%= contact_form.label :subject %><br />
    <%= contact_form.text_field :subject %>
  </div>
  <div class="field">
    <%= contact_form.label :message %><br />
    <%= contact_form.text_area :message %>
  </div>
  <div class="actions">
    <%= contact_form.submit %>
  </div>
<% end %>

app/views/contacts/new.html.erb
<style>

h1{
	color: blue;
	padding-top: 8px;
	padding-left: 8px;
  }

.box   {
			width:170px;
			height:35px;
			background-color:yellow;
			box-shadow: 10px 10px 5px #888888;
			border-radius: 10px;
		}

</style>
<div class="box">
<h1>Contacts Us</h1></div>
<br><br>	

<%= render 'form' %>

app/views/home/index.html.erb
<!--include current_or_guest_user
include guest_user
include logging_in
include create_guest_user -->

<h1>Hello Rails..!!</h1>
<h2> Welcome Gagan's Blog</h2>
<style>
.menus a{
			padding-right: 10px;
			color: blue;
			font-size: 15px;
		}
img {
    -webkit-box-shadow: 3px 3px 3px #7C7C7C;
    box-shadow: 5px 5px 5px #7C7C7C;
    }
</style>
<%= image_tag "photo.jpg", size: "109x106" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<style>
.menus a{
  padding-right: 10px;
  color: blue;
  font-size: 15px;
}
</style>
<body>
<body style="background: aqua;">

<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<%= yield %>

</body>

 <br><br><br><b><div class="menus">
 <div style="height:20px; margin-top:2px;background-color:#FFA500;text-align:center;font-size:15px;border-radius:15px;padding-right: 0px" id="footer">
<%= link_to "Home", '/' %>
<%= link_to "My Blog", posts_path %>
<%= link_to "About Us", about_us_path %>
<%= link_to "Contact Us", new_contact_path %> </div>
</div> </html>	

app/views/posts/_form.html.erb
<% @post.tags.build %>
<%= form_for(@post) do |post_form| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= post_form.label :name %><br />
    <%= post_form.text_field :name %>
  </div>
  <div class="field">
    <%= post_form.label :title %><br />
    <%= post_form.text_field :title %>
  </div>
  <div class="field">
    <%= post_form.label :content %><br />
    <%= post_form.text_area :content %>
  </div>
  <h2>Tags</h2>
  <%= render :partial => 'tags/form',
             :locals => {:form => post_form} %>
  <div class="actions">
    <%= post_form.submit %>
  </div>
<% end %>

app/views/posts/about_us.html.erb
<html>

<body>

<div id="header" style="background-color:#FFA500;border-radius:10px;">
		<h1 style="text-align:center;margin-bottom:5px;line-height: 30px;"> About Us..</h1>
	</div>
	
	<div id="content"  style="height:750px; width:1200px;padding:10px;border-radius:15px;border:8px solid blue;background-color:green;font-size:12pt;color:white;">
Priya Softweb Solutions is a custom software development company that serves clients of all sizes. We have a strong performance record in offering quality software development services demonstrated by ISO 9001:2008 certification and Microsoft Gold Certified partnership. We deliver end-to-end business solutions to maximize return on investment for our reputed clientele. We are a process focused company leveraging best of breed methodologies to enable our clients realize superior business performance.
<p><div id="content">
Our robust IT solutions not only help our clients strengthen their global footprint but also stay ahead of their competitors. We have a team of software developers with rich experience and deep technical expertise to deliver bespoke solutions to you.</p></div></div>
</div>
</body>

</html>

app/views/posts/edit.html.erb
<h3 style="text-align:center;background-color:yellow;color:red"> Edit page (views/post/edit) </h3>

<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<style>
.xyz a{
  padding-right: 10px;
  font-size: 15px;
}
.abc {color: blue;}
</style>

<h3 style="text-align:center;background-color:yellow;color:red"> Index page<div class="abc">(views/post/index) </div></h3>


<h1>Listing posts</h1>

<table border="2" bgcolor="orange">
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br>
<b>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
 <h3 style="text-align:center;background-color:yellow;color:red"> Show page (views/post/show) </h3>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>
 
<p>
  <b>Title:</b>
  <%= @post.title %>
</p>
 
<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
 
 <p>
  <b>Tags:</b>
  <%= @post.tags.map { |t| t.name }.join(", ") %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<br />
 
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %> |

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Tag:' %>
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>